
package com.nerzid.CommentGenerator;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

/**
 * This annotation means, below comment is generated by NerzidCommentGenerator
 * @author AutoCommentGeneratorNerzid
 * 
 * @version 1
 * @see www.nerzid.com
 * 
 */
@Documented
@Target(ElementType.METHOD)
public @interface NerzidComment {
    
    String comment() default "AutomatedNerzıdComment Inserted here";
    String fasafiso = "Hellooooooooo";
    
}
